#!/usr/bin/python3
import os
import subprocess
import json
import time
import requests


def run_device_command(cmd):
    cmd = cmd.strip().split()
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout if result.returncode == 0 else result.stderr

json_file = "/etc/cfg.json"

with open(json_file) as file:
    data_cfg = json.load(file)

ssid = data_cfg['ssid']
password = data_cfg['password']
host_name = data_cfg['host']
port = data_cfg['port']
device_id = data_cfg['device_id']
desktop_url = f'http://{host_name}:{port}/device_register'
alive_flag = True


while True:
    out = run_device_command(f'iwgetid')
    print(out)
    if ssid not in out:
        alive_flag = False
        if os.path.exists('/etc/wifi_connected'):
            os.remove('/etc/wifi_connected')
        os.system(f'nmcli d wifi connect "{ssid}" password "{password}"')
        time.sleep(1)
    else:
        if alive_flag is False:
            print('Reconnect')
            # os.system('systemctl restart usb-manager')
            alive_flag = True
        os.system('touch /etc/wifi_connected')
        try:
            response = requests.post(desktop_url, json={'device_id': device_id}, timeout=1)
            if response.status_code == 200:
                time.sleep(10)
            else:
                time.sleep(1)
        except:
            pass
