#!/bin/sh

work_dir='/data'
usb_backingfile="${work_dir}/usb_partition.img"

modprobe g_mass_storage -r

mount "${usb_backingfile}" /mnt/

if [ -f '/mnt/cfg.json' ]; then
    cp '/mnt/cfg.json' '/etc/'
fi

umount /mnt/
